### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by ryanwclark1** [tefra/xsdata-pydantic#3]
@tefra, please excuse the use of "Issues" for this communication but I didn't see an email.  Anything you are looking for help with on the xsdata or xsdata-pydantic projects?

**Comment by tefra** [comment]
Hi @ryanwclark1

It's getting there, I still have to solve a couple of [failures](https://github.com/tefra/xsdata-pydantic/actions/runs/2059145206) I am gonna need you for testing 👍

**Comment by ialarmedalien** [comment]
What's the current status of this project and what is to be done?

**Comment by tefra** [comment]
It's been a while, I tried some months ago to push this one for release but I got a few blocking issues from pydantic with the w3c test suite and some of my samples. I haven't checked since then to be honest

Currently it's not the top priority but in #8 someone managed to make it work for them, but If I don't resolve these issues with pydantic I can't really release it.

**Comment by tefra** [comment]
The first release is live, not everything works, the most complex test suite in the samples repo is still broken but the rest work as expected!!
